version: "5.0.1"

services:
  pg_service:
    image: postgres:alpine
    container_name: pg
    restart: always
    entrypoint:
      POSTGRES_PASSWORD:"lelouch0225"
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    image: gym_image:latest
    container_name: gym_con
    restart: always
    command:
      - "python3 main.py"
    depends_on:
      - pg_service


volumes:
  pgdata:

